{{- $cn := printf "%s-service.%s.svc" .Release.Name .Release.Namespace }}
{{- $cert := genSelfSignedCert $cn nil (list $cn) 3650 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-tls
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  server.cert: {{ $cert.Cert | b64enc }}
  server.key: {{ $cert.Key | b64enc }}
