{{- if .Values.osqueryAgent.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-enroll-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-enroll-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
stringData:
  enroll_secret: placeholder
{{- end }}
